### ISSUE TITLE
This script doesn't seem to work on DSM Version: 7.2.1-69057 Update 3

### ISSUE THREAD

**Issue by jowinthe** [007revad/Synology_DSM_reinstall#9]
I could not get this script to work on DSM Version: 7.2.1-69057 Update 3.  The script exits immediately with no messages.

**Comment by 007revad** [comment]
What is the exact command you are typing?

What shell or terminal are you using?

**Comment by jowinthe** [comment]
Hi,

I was running the script via Task Scheduler, as described here:
https://github.com/007revad/Synology_DSM_reinstall/tree/main 

I created a task with "root" user and the path to the file /syno_dsm_reinstall.sh

It seems like the script is initiated, but then exits almost immediately.


 


Den Fri, 01 Dec 2023 11:06:40 -0800, Dave Russell ***@***.***> skrev:
 
 

What is the exact command you are typing?

What shell or terminal are you using?

**Comment by 007revad** [comment]
When you run a script via task scheduler it appears to finish immediately, but it finishes running in the background. 

You can see the output from the script in task scheduler: 
1. In task scheduler select the task.
2. Click "Action > View Result".
3. Click the "View Details" link.

**Comment by jowinthe** [comment]
I just ran the new .sh file (with the "# Check script is running as root" mod.). Still no joy. It takes a bit longer to finish, but no messages, and the DSM version remains the same. Still "unable to re-install due to older version" message.





Den Sat, 02 Dec 2023 00:47:29 +0000, "Jon Winther-Hansen" ***@***.***> skrev:
 
Hi,

I was running the script via Task Scheduler, as described here:
https://github.com/007revad/Synology_DSM_reinstall/tree/main 

I created a task with "root" user and the path to the file /syno_dsm_reinstall.sh

It seems like the script is initiated, but then exits almost immediately.


 


Den Fri, 01 Dec 2023 11:06:40 -0800, Dave Russell ***@***.***> skrev:
 
 

What is the exact command you are typing?

What shell or terminal are you using?

**Comment by jowinthe** [comment]
For some reason the Action > View Result is greyed out.  I entered my e-mail in the "Send run details by e-mail".
This is what I got:

Task Scheduler has completed a scheduled task.

Task: dsm_fix
Start time: Sat, 02 Dec 2023 02:15:01 +0100
Stop time: Sat, 02 Dec 2023 02:15:58 +0100
Current status: 127 (Interrupted)
Standard output/error:
/bin/bash: /volume: No such file or directory
From DS



My DSM UI seems a bit sluggish after the upgrade from 6 to 7.2.1, and that's why I want to re-install the system. Maybe that has something to do with why the script is not functioning properly?



Den Fri, 01 Dec 2023 17:03:25 -0800, Dave Russell ***@***.***> skrev:
 
 

When you run a script via task scheduler it appears to finish immediately, but it finishes running in the background.

You can see the output from the script in task scheduler:


	In task scheduler select the task.
	Click "Action > View Result".
	Click the "View Details" link.

**Comment by 007revad** [comment]
> Current status: 127 (Interrupted) 
> Standard output/error: /bin/bash: /volume: No such file or directory

Edit the scheduled task and change /volume/ to /volume1/

**Comment by jowinthe** [comment]
I just ssh into the NAS, and then figured out what you say below, that the "volume 1" should read "volume1" in the path. (even though it's listed as "volume 1" in the Storage Manager...
Thanks for the swift replies, and for the script itself!

Jon


Den Fri, 01 Dec 2023 17:42:27 -0800, Dave Russell ***@***.***> skrev:
 
 


Current status: 127 (Interrupted)
Standard output/error: /bin/bash: /volume: No such file or directory


Edit the scheduled task and change /volume/ to /volume1/
